# config.yaml

# 接口地址
base_url: "https://candfans.jp/api/user/get-entry-plans"

# HTTP 头，一律保持键名小写
headers:
  accept: "application/json"
  accept-language: "zh-CN,zh;q=0.9,en-US;q=0.8,en;q=0.7"
  priority: "u=1, i"
  referer: "https://candfans.jp/mypage/plan/admission"
  sec-ch-ua: "\"Google Chrome\";v=\"137\", \"Chromium\";v=\"137\", \"Not/A)Brand\";v=\"24\""
  sec-ch-ua-mobile: "?0"
  sec-ch-ua-platform: "\"Windows\""
  sec-fetch-dest: "empty"
  sec-fetch-mode: "cors"
  sec-fetch-site: "same-origin"
  user-agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36"
  x-xsrf-token: "Please input your xsrf token here"

cookie: "Please input your cookie here"
get_users_url: "https://candfans.jp/api/user/get-users"
get_timeline_url: "https://candfans.jp/api/contents/get-timeline"
download_dir: "./downloads"